name: compile_deploy_html
on:
  push:
    branches:
      - master
jobs:
  html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.3.2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'
      - name: Poetry install
        run: poetry install
      - name: Produce publications html
        run: poetry run python bib_to_html.py
      - name: move
        run: mkdir -p github_artifacts && mv publications.html ./github_artifacts/
      - name: Upload html as artifact
        uses: actions/upload-artifact@v3
        with:
          name: publications.html
          path: ./github_artifacts
  deploy:
    # Edit here if compiling multiple papers
    needs: [html]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build_html
          force_orphan: true
