# Github workflow to compile latex and deploy the pdf to an orphan branch.
# Davide Gerosa (2021) https://github.com/dgerosa

# Edit the DIR and FILE variables with the location of the latex file.
# Place the yml file in a directory called .github/workflows

# The latest compiled pdf is made available at e.g.
# https://github.com/dgerosa/[repositoryname]/blob/build/[filename].pdf

# You can also add a badge to your README:
# [![compile_deploy_latex](https://github.com/dgerosa/[repositoryname]/actions/workflows/compile_deploy_latex.yml/badge.svg)](https://github.com/dgerosa/[repositoryname]/actions)

# To compile multiple papers, duplicate the job called "paper" with different FILE/DIR names and add the "needs" line in the "deploy" job accordingly  

name: compile_deploy_latex
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install moderncv
        run: |
          apt update && apt install -y git
          git clone https://github.com/moderncv/moderncv/tree moderncv
          cd moderncv
          git checkout fa3ebb6
          rm /usr/share/texlive/texmf-dist/tex/latex/moderncv/*
          cp -r * /usr/share/texlive/texmf-dist/tex/latex/moderncv/
      - name: Compile Latex
        run: latexmk -pdflua cv.tex
      - name: move
        run: mkdir -p github_artifacts && mv cv.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: ./github_artifacts
  deploy:
    # Edit here if compiling multiple papers
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
